"""Build viewer/icons.svg, an SVG sprite of the Lucide icons the viewer uses.

The icons come from the `lucide-static` npm package at a pinned version, checked against a pinned
SHA-256 before anything is extracted. Each icon becomes one `<symbol>` whose id is its Lucide name,
used from the viewer as:

    <svg class="icon" aria-hidden="true"><use href="/viewer/icons.svg#circle-check"/></svg>

Lucide is ISC-licensed, with some icons MIT-licensed from Feather; the package's licence text is
copied to viewer/icons.LICENCE beside the sprite.

To add an icon, append its canonical Lucide name to ICONS (search at https://lucide.dev; an alias
such as `circle-help` is refused) and rerun. To upgrade, change VERSION and SHA256 together.

Usage: uv run python workbench/scripts/build_icons.py
"""

from __future__ import annotations

import hashlib
import io
import json
import sys
import tarfile
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VIEWER_DIR = ROOT / "viewer"
SPRITE = VIEWER_DIR / "icons.svg"
LICENCE = VIEWER_DIR / "icons.LICENCE"

VERSION = "1.48.0"
SHA256 = "3c2ecda3d25f6a9692d83f8036d9a526f7da584a51af74cd16eda4498c5c33d8"
TARBALL = f"https://registry.npmjs.org/lucide-static/-/lucide-static-{VERSION}.tgz"
TIMEOUT_S = 60

ICONS = [
    # outcome statuses (js/common.js STATUS_ICONS)
    "circle-check",  # succeeded
    "circle-minus",  # abstained
    "circle-arrow-right",  # referred
    "circle-x",  # failed
    "circle-pause",  # suspended
    # modes
    "microscope",  # Inspect
    "message-square",  # Chat
    "bot",  # Agents
    # controls
    "play",  # Run
    "send-horizontal",  # Send
    "message-square-plus",  # New conversation
    "book-open",  # Glossary
    "x",  # Close
    "circle-question-mark",  # help buttons
    "copy",  # Copy
    "check",  # Copied
    "download",  # Download
    "arrow-right",  # Inspect link
    "braces",  # JSON tabs
    # lists and envelope
    "rotate-ccw-clock",  # stored runs, conversations
    "triangle-alert",  # problem
    "corner-down-right",  # delegated to
    "git-branch",  # delegations
    "git-compare",  # version change
    "link",  # grounded_on
    "fingerprint-pattern",  # input hash
]

SVG_NS = "http://www.w3.org/2000/svg"
# Presentation attributes every Lucide icon carries; kept on each symbol so the sprite renders
# correctly without the viewer's stylesheet.
SYMBOL_ATTRS = ("viewBox", "fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin")


def fetch() -> bytes:
    with urllib.request.urlopen(TARBALL, timeout=TIMEOUT_S) as response:
        data: bytes = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        sys.exit(f"SHA-256 mismatch for {TARBALL}: expected {SHA256}, got {digest}")
    return data


def read_member(tar: tarfile.TarFile, name: str) -> bytes:
    member = tar.extractfile(f"package/{name}")
    if member is None:
        sys.exit(f"{name} missing from lucide-static {VERSION}")
    return member.read()


def to_symbol(name: str, svg: bytes) -> str:
    root = ET.fromstring(svg)
    for node in root.iter():  # drop the namespace so each child is not re-declared with xmlns
        node.tag = node.tag.removeprefix(f"{{{SVG_NS}}}")
    attrs = " ".join(f'{a}="{root.attrib[a]}"' for a in SYMBOL_ATTRS)
    children = "".join("\n    " + ET.tostring(child, encoding="unicode").strip() for child in root)
    return f'  <symbol id="{name}" {attrs}>{children}\n  </symbol>'


def main() -> None:
    with tarfile.open(fileobj=io.BytesIO(fetch()), mode="r:gz") as tar:
        canonical = json.loads(read_member(tar, "icon-nodes.json"))
        unknown = [name for name in ICONS if name not in canonical]
        if unknown:
            sys.exit(f"not canonical Lucide {VERSION} icon names: {', '.join(unknown)}")
        symbols = [to_symbol(name, read_member(tar, f"icons/{name}.svg")) for name in ICONS]
        licence = read_member(tar, "LICENSE")

    header = (
        f"<!-- Lucide icons, lucide-static {VERSION}, ISC (some MIT via Feather); see icons.LICENCE.\n"
        "     Generated by workbench/scripts/build_icons.py; do not edit by hand. -->\n"
    )
    body = "\n".join(symbols)
    SPRITE.write_text(f'{header}<svg xmlns="{SVG_NS}">\n{body}\n</svg>\n', encoding="utf-8")
    LICENCE.write_bytes(licence)
    print(f"wrote {len(symbols)} icons to {SPRITE.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
