"""Render CONFORMANCE.md from the requirements register and a pytest-json-report run.

The traceability rule: a registered requirement is

- **substantiated**  if at least one test marked with its identifier passed and none failed;
- **contradicted**   if any test marked with its identifier failed;
- **unsubstantiated** otherwise — no marked test, or only skipped tests.

A report in which most rows are honestly unsubstantiated is the intended first governance
artefact. "Substantiated by an example-based test" is not a conformance claim; the footer says so.

Usage, from the repository root (one test session covers the whole workspace):
    uv run pytest --json-report --json-report-file=workbench/.report.json
    uv run python workbench/scripts/conformance_report.py            # writes CONFORMANCE.md
    uv run python workbench/scripts/conformance_report.py --check    # exit 1 if the table changes
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
REGISTER = ROOT / "docs" / "requirements.yaml"
REPORT = ROOT / ".report.json"
OUTPUT = ROOT / "CONFORMANCE.md"

SUBSTANTIATED = "substantiated"
CONTRADICTED = "contradicted"
UNSUBSTANTIATED = "unsubstantiated"

TABLE_START = "<!-- conformance-table:start -->"
TABLE_END = "<!-- conformance-table:end -->"


def load_register(path: Path = REGISTER) -> list[dict[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    reqs: list[dict[str, Any]] = data["requirements"]
    return reqs


def load_report(path: Path = REPORT) -> dict[str, Any]:
    if not path.is_file():
        sys.exit(
            f"{path} not found; run `uv run pytest --json-report --json-report-file={path}` first"
        )
    report: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    return report


def tests_by_requirement(report: dict[str, Any]) -> dict[str, list[tuple[str, str]]]:
    """requirement id -> [(nodeid, outcome)], read from the metadata the conftest hook wrote."""
    index: dict[str, list[tuple[str, str]]] = {}
    for test in report.get("tests", []):
        ids = (test.get("metadata") or {}).get("requirements") or []
        for rid in ids:
            index.setdefault(rid, []).append((test["nodeid"], test["outcome"]))
    return index


def verdict(tests: list[tuple[str, str]]) -> str:
    outcomes = {o for _, o in tests}
    if "failed" in outcomes or "error" in outcomes:
        return CONTRADICTED
    if "passed" in outcomes:
        return SUBSTANTIATED
    return UNSUBSTANTIATED


def _short(nodeid: str) -> str:
    return nodeid.split("::")[-1]


def render_table(
    register: list[dict[str, Any]], index: dict[str, list[tuple[str, str]]]
) -> tuple[str, dict[str, int]]:
    rows = ["| ID | Source | Title | Verdict | Tests |", "|---|---|---|---|---|"]
    counts = {SUBSTANTIATED: 0, CONTRADICTED: 0, UNSUBSTANTIATED: 0}
    for req in register:
        tests = index.get(req["id"], [])
        v = verdict(tests)
        counts[v] += 1
        marker = {SUBSTANTIATED: "✅", CONTRADICTED: "❌", UNSUBSTANTIATED: "⬜"}[v]
        names = (
            ", ".join(
                f"`{_short(n)}`" + ("" if o == "passed" else f" ({o})") for n, o in sorted(tests)
            )
            or "—"
        )
        parent = f" (under {req['parent']})" if req.get("parent") else ""
        rows.append(
            f"| {req['id']} | {req['source']}{parent} | {req['title']} | {marker} **{v}** | {names} |"
        )
    return "\n".join(rows), counts


def git_commit() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout.strip()
    except OSError, subprocess.CalledProcessError:
        return "unknown"


def render(register: list[dict[str, Any]], report: dict[str, Any]) -> str:
    index = tests_by_requirement(report)
    unregistered = sorted(set(index) - {r["id"] for r in register})
    table, counts = render_table(register, index)
    summary = report.get("summary", {})
    created = datetime.fromtimestamp(report.get("created", 0), tz=UTC).isoformat(timespec="seconds")
    head = f"""# Conformance report

**Generated:** {created} · **Commit:** `{git_commit()}` · **Python:** {platform.python_version()} · **Test run:** {summary.get("passed", 0)} passed, {summary.get("failed", 0)} failed, {summary.get("skipped", 0)} skipped of {summary.get("total", 0)}

This file is generated by `scripts/conformance_report.py` from `docs/requirements.yaml` and a
`pytest-json-report` run. Do not edit it by hand.

## How to read it

Each row is a requirement in the register. The verdict applies one rule, the traceability rule:

- **substantiated** — at least one test marked `@pytest.mark.requirement("<ID>")` passed in this run and none failed;
- **contradicted** — a test marked with the identifier failed;
- **unsubstantiated** — no test claims the identifier, or every claiming test was skipped.

*Substantiated* means an example-based test exercised one path through the requirement. It is
**not** a conformance claim, an evaluation result, or evidence that the requirement is met in
general. Rows marked unsubstantiated are the honest default and the point of publishing this file:
the Blueprint's Appendix D records implementers' stated intentions; this table records what a
test run actually showed.

`source: blueprint` rows use the Blueprint's own identifiers and titles (§7). `source: project`
rows are identifiers this project introduced (the R3.n decomposition from
`experiments/standards-advisor`, and `DD-*` for the contract itself); the Blueprint does not use
them.

## Summary

| Verdict | Count |
|---|---|
| substantiated | {counts[SUBSTANTIATED]} |
| contradicted | {counts[CONTRADICTED]} |
| unsubstantiated | {counts[UNSUBSTANTIATED]} |

"""
    body = f"{TABLE_START}\n{table}\n{TABLE_END}\n"
    if unregistered:
        body += f"\n> ⚠️ Tests claimed identifiers not in the register: {', '.join(unregistered)}. Register them or remove the markers.\n"
    foot = """
## Attestation

This report is not signed. The intent is to attest it with in-toto or Sigstore once the project
has a release process; until then, the commit hash above and the CI job that regenerates this file
are the only link between the table and the code (see docs/adr/0006-dependency-tiering.md,
"Rejected for v0").

## Regenerating

```sh
uv run pytest --json-report --json-report-file=workbench/.report.json
uv run python workbench/scripts/conformance_report.py
```

CI runs the same two commands with `--check`, which fails if the table body differs from the
committed file (the timestamp header is excluded from the comparison).
"""
    return head + body + foot


def table_body(text: str) -> str:
    start, end = text.find(TABLE_START), text.find(TABLE_END)
    return text[start:end] if start >= 0 and end >= 0 else text


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--report", default=str(REPORT))
    ap.add_argument("--output", default=str(OUTPUT))
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if the committed table body would change"
    )
    ns = ap.parse_args(argv)
    text = render(load_register(), load_report(Path(ns.report)))
    out = Path(ns.output)
    if ns.check:
        if not out.exists() or table_body(out.read_text(encoding="utf-8")) != table_body(text):
            print(
                f"{out.name} is stale; regenerate with scripts/conformance_report.py",
                file=sys.stderr,
            )
            return 1
        print(f"{out.name} is current")
        return 0
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
