// --- Glossary: BEGIN --------------------------------------------------------------------
// The one source of the page's explanatory text: the "?" tips and the Glossary dialog both read
// it. Definitions follow schema/data_director.yaml; keep them in step when the contract changes.
// A key "status:<value>", "mode:<value>" or "derivation:<value>" explains one enum value.
export const GLOSSARY = {
  "envelope": { term: "envelope", text: "The single JSON document a run returns: the outcome, the payload if the agent succeeded, the evidence it rests on, telemetry, and identifiers and timestamps. The conductor, not the agent, fills everything the agent did not decide, so an agent cannot mislabel its own run. One request produces exactly one envelope." },
  "conductor": { term: "conductor", text: "The harness component that invokes an agent. It applies the policy gate and the input check, calls the agent, fills identifiers, timestamps, telemetry and grounding mode, and runs the grounding linter over the result." },
  "linter": { term: "grounding linter", text: "Checks every envelope against the rules of the agent's grounding mode before it is stored. A violation turns succeeded into failed." },
  "agent": { term: "agent", text: "A registered component that takes one input document and returns an outcome, with a payload if it succeeded. The list comes from the registry manifest (GET /agents), grouped by the prefix of each agent's id; the version shown is the one running now." },
  "sample": { term: "sample input", text: "An example input document shipped with the workbench. Choosing one fills the input form, which can then be edited; Blank starts from an empty form. Only samples of the chosen input class are listed." },
  "input-form": { term: "input form", text: "The input to send, as a form built from the input class's schema in the contract (schema/data_director.yaml). Its fields and required fields are the class's slots. The form is checked before sending, and the workbench checks the input again before any agent runs." },
  "stored-runs": { term: "stored runs", text: "Envelopes kept in the workbench's append-only JSONL store, newest first, including conversation turns and delegated invocations. Select one to load it again." },
  "input": { term: "input", text: "The document the agent was given. The workbench stores it beside the envelope (request.json) and the envelope records its hash, but this page shows it only for runs sent, or conversations opened, in this browser tab." },
  "inspect": { term: "Inspect", text: "Run one agent on one input and examine the envelope it returns: outcome, payload, evidence and telemetry. The deterministic test bench for an agent's inputs and outputs." },
  "chat": { term: "Chat", text: "Hold a conversation with one agent, usually the orchestrator. Each turn is one invocation with its own stored envelope; every reply names the agent and version that produced it and links to that envelope in Inspect." },
  "conversation": { term: "conversation", text: "A sequence of turns sharing one conversation_id. There is no separate conversation store: a conversation is read back from the stored invocations that carry its id (GET /conversations)." },
  "conversation_id": { term: "conversation_id", text: "The UUIDv7 shared by every turn of a conversation, and by every invocation delegated during it. Open chat.html?conversation_id=… to reopen the conversation." },
  "turn": { term: "turn", text: "One exchange in a conversation: what was sent (a Message, or any input the agent accepts) and the envelope that came back. A turn is exactly one invocation, so the policy gate, the grounding linter, storage and provenance apply to it as to any run." },
  "message": { term: "Message", text: "The input class of a conversational agent: this turn's text (message_text) and the conversation so far (history). The history is part of the input, so the input hash covers everything the agent was shown." },
  "reply": { term: "Reply", text: "The payload class of a conversational agent: reply_text, and reply_derivation recording whether a template or a model wrote it." },
  "orchestrator": { term: "orchestrator", text: "An agent in grounding mode delegation: it answers by asking the workbench to invoke other agents and relaying what they return. The Blueprint's Data Director is one. Chat selects the first such agent by default." },
  "delegation": { term: "delegation", text: "An invocation an orchestrator asked the workbench to run for it. The orchestrator never calls another agent directly: the workbench runs the child as an ordinary governed invocation, stores it with parent_invocation_id, and records it in the parent envelope's delegations, which is all the reply may cite besides its input." },
  "parent_invocation_id": { term: "parent_invocation_id", text: "On a delegated invocation, the invocation that delegated it. Set only by the conductor, never by a caller." },
  "version-change": { term: "version change", text: "The agent answered at a different version from an earlier turn of the same conversation, for example after it was rebuilt and restarted. Behaviour either side of the line comes from different code." },
  "payload": { term: "payload", text: "The agent's answer, present only when the outcome is succeeded. Its shape is set by its payload class, shown as the schema_class beside the heading; every payload records what it rests on in grounded_on." },
  "schema_class": { term: "schema_class", text: "The name of the schema class a document conforms to. The conductor uses it to check an agent accepts its input; the viewer uses it to find the schema that renders a payload." },
  "evidence": { term: "evidence", text: "One row per thing the run retrieved or rested on, including the input itself: where it came from, when, and a hash of its canonicalised content. Where a row carries the content its hash covers, the grounding linter re-hashes it (E1), so what the payload is shown to cite is what was retrieved." },
  "telemetry": { term: "telemetry", text: "Run measurements filled by the conductor: the OpenTelemetry trace, the model called and its token counts, and slots for energy use, which are null and not_measured for now." },
  "problem": { term: "problem", text: "RFC 9457 Problem Details, present when the outcome is failed or suspended: a problem type URI, a title, a detail and an HTTP status. For suspended it also says when, or on what condition, the run may resume." },
  "requirement": { term: "requirement id", text: "A requirement the agent declares it addresses: a Blueprint requirement (R3, R3.1, …) or a project one, as listed in docs/requirements.yaml. The conformance report traces each to the tests that substantiate it." },
  "accepts": { term: "accepts", text: "The input classes (schema_class values) this agent accepts. An input of any other class fails with input-not-accepted." },
  "unavailable": { term: "unavailable agent", text: "An agent that is registered but could not be built, for example one awaiting a port. It is listed so its reason can be read; it cannot be run." },
  "human-review": { term: "requires_human_review", text: "Always true. Every workbench output needs a person to review it before it is acted on. It is emitted as a constant so no consumer can produce an envelope claiming otherwise." },
  "status": { term: "outcome status", text: "What the run came to: succeeded, abstained, referred, failed or suspended. Abstaining is an honest answer, not an error." },
  "status:succeeded": { term: "succeeded", text: "The agent produced a payload it stands behind, and the payload passed the grounding linter." },
  "status:abstained": { term: "abstained", text: "The agent declined to recommend; reason_code says why. An equal output to succeeded, not an error." },
  "status:referred": { term: "referred", text: "The agent hands the decision to the human role named in referred_to; reason_code says why." },
  "status:failed": { term: "failed", text: "The agent or the harness could not complete, or the payload broke a grounding rule. The problem block carries RFC 9457 details." },
  "status:suspended": { term: "suspended", text: "The run awaits an external condition; the problem block carries the condition for resuming." },
  "reason_code": { term: "reason_code", text: "Why the agent abstained or referred, from a fixed vocabulary such as no_candidates_retrieved, registry_unavailable, insufficient_input or requires_human_judgement. Required for those two statuses." },
  "referred_to": { term: "referred_to", text: "The human role a referred outcome hands the decision to, for example data_steward." },
  "agent_version": { term: "agent_id@agent_version", text: "Which agent ran, and which version of it." },
  "acting_for": { term: "acting_for", text: "The person the run acted for, or the accountable role where it acted for an institution. The conductor records it from the workbench's sign-in boundary, never from the request, and a delegated run acts for its parent's. The agent is not told who it is." },
  "assurance:asserted": { term: "asserted", text: "The workbench has no sign-in yet. Its operator configured this name, and nobody checked it. On a shared workbench every run shows the operator, whoever started it." },
  "grounding_mode": { term: "grounding_mode", text: "The grounding contract the agent declares: what its output may rest on. The conductor records it from the agent's specification, never from the agent's output, and the grounding linter applies that mode's rules." },
  "mode:retrieval": { term: "retrieval", text: "The agent retrieves external records before any model call, and every identity it asserts was retrieved (linter rules G1–G4)." },
  "mode:input_only": { term: "input_only", text: "The agent works only over the input it was given. No retrieval may appear; a model may be called; every grounding reference is the input's hash (linter rules R1–R3)." },
  "mode:none": { term: "none", text: "The agent is deterministic over its input: no retrieval and no model call (linter rules R1–R3 and N1)." },
  "mode:delegation": { term: "delegation", text: "The agent works over its input and the envelopes of invocations it delegated through the workbench. No retrieval may appear; a model may be called; every grounding reference is the input's hash or a delegation the conductor recorded (linter rules R1, D1–D3, G4)." },
  "completed_at": { term: "completed_at", text: "When the conductor finished the run, shown in local time. Hover over the time for the full timestamp." },
  "invocation_id": { term: "invocation_id", text: "The run's identifier: a UUIDv7, time-ordered so the append-only store sorts without an index. Add ?invocation_id=… to the Inspect page's address to reload the run." },
  "derivation": { term: "derivation", text: "How a payload field's value came about. Each agent declares it per field in its manifest (derivations). Where a model may write a field, the badge reads a sibling field recording what actually happened, so a template fallback is not badged as model output." },
  "derivation:model": { term: "model", text: "Written by a language model. Check it against the evidence before relying on it." },
  "derivation:template": { term: "template", text: "Produced deterministically from retrieved fields by a fixed template." },
  "derivation:lexical": { term: "lexical", text: "Produced by a keyword rule over retrieved fields." },
  "derivation:registry": { term: "registry", text: "Read directly from a curated registry field." },
  "derivation:verified": { term: "verified", text: "The unbadged default: set by the harness or read from a registry, not generated." },
  "source_id": { term: "source_id", text: "What was retrieved: a registry record identifier, or input:<invocation_id> for the input document itself." },
  "cited": { term: "cited", text: "The row's content_hash appears in the payload's grounded_on, so the payload rests on it. A visual cross-check only; the grounding linter is what enforces it." },
  "grounded_on": { term: "grounded_on", text: "The list in a payload, and in any item that asserts an identity, naming what it rests on: each entry a source_id and a content_hash. The only place a payload may assert an external identity; what an entry names (a record's name, status) is read from the evidence row with the same source_id and content_hash." },
  "retrieved_at": { term: "retrieved_at", text: "When the record was retrieved." },
  "canonicalisation": { term: "canonicalisation", text: "The registered rule that projects a record to bytes before hashing, for example dd-input-json-v1 for the input document. A name's bytes never change, so a hash stays reproducible." },
  "snapshot_ref": { term: "snapshot_ref", text: "Which copy of the registry answered, for example snapshot:2026-09-04 or live. Blank where no registry was involved." },
  "content_hash": { term: "content_hash", text: "The hash of the canonicalised record, prefixed by its algorithm (sha256). Canonicalise the record under the same rule and hash it again to check it." },
  "trace_id": { term: "trace_id", text: "The OpenTelemetry trace identifier for the run (32 hex characters). Look it up in a trace viewer to see the run's spans." },
  "model_id": { term: "model_id", text: "The language model the agent called, or null if it called none." },
  "tokens": { term: "tokens in / out", text: "Tokens sent to and received from the model; blank if no model was called." },
  "energy_estimate_j": { term: "energy_estimate_j", text: "Estimated energy use of the run, in joules. Not yet measured, so null." },
  "energy_method": { term: "energy_method", text: "How the energy figure was obtained: not_measured, estimated or measured." },
};
// --- Glossary: END ----------------------------------------------------------------------
